image: "archlinux:latest"

stages:
  - build

build-smod-linux-x64:
  stage: build
  before_script:
    - pacman-key --init
    - pacman -Syu --needed --noconfirm ninja cmake gcc gcc-libs glibc frameworkintegration gcc-libs glibc kcmutils kcolorscheme kconfig kcoreaddons kdecoration kguiaddons ki18n kiconthemes kirigami kwidgetsaddons kwindowsystem qt6-base qt6-declarative qt6-svg extra-cmake-modules kwin kwin-x11  kdoctools krunner plasma-wayland-protocols wayland wayland-protocols python xorg-xwayland pkgconf
  script:
    - cmake -G Ninja -DBUILD_TESTING=ON -B build . 
    - cmake --build build 
    - DESTDIR=out cmake --install build
    - cmake --prefix /usr --install build
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 6 mos
    paths: 
      - out/

build-smodglow-linux-x64:
  stage: build
  needs:
    - job: build-smod-linux-x64
  before_script:
    - cd ./smodglow
  script:
    - cmake -G Ninja -B build .
    - cmake --build build
    - DESTDIR=outsmodglow cmake --install build
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 6 mos
    paths:
      - outsmodglow/
